
'use client';

import type {Metadata} from "next";
//import {Geist, Geist_Mono} from "next/font/google";
import '@/app/assets/CSS/style.css';
import {showTopArrow} from "@/lib/navigation";
import React from "react";
import {TopArrow} from "./components/TopArrow";
import {Contacts} from "./components/Contacts";
import {Menu} from "./components/Menu";
import {LeftMenu} from "./components/LeftMenu";
//import UpWhiteArrowOcreCircle from "@/app/assets/images/UpWhiteArrowOcreCircle.png";



/*
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
*/

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	/*
	 * This allows us to do a check whenever there is a scroll event in the window
	 * which we want to do in order to make the navigation arrow that scrolls back to the top of the page.
	 */
	React.useEffect(() => {
		window.addEventListener('scroll', showTopArrow);

		// Cleanup function to remove the event listener
		return () => {
			window.removeEventListener('scroll', showTopArrow);
		};
	}, []);		// Empty dependency array ensures it runs once on mount

	//const arrowRef = React.useRef(null);
	return (
		<html lang="en">
			<body>
				<div id="Home"></div>
				<Menu>
					<LeftMenu></LeftMenu>
				</Menu>
				{children}
				<TopArrow />
				{/*
				 * Pour plus tard, lorsque notre architecture est en place.
				 * <Contacts />
				 * */}

			</body>
		</html>
	);
}
