
import type {Metadata} from "next";
//import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import '@/app/assets/CSS/';
import showTopArrow from "@/lib/navigation";

/*
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
*/

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body onScroll={showTopArrow}>

				{children}
				<footer className={"verticalBottomRight"}>
					<img id="topArrow" className={"arrow"} src="@/assets/images/UpWhiteArrowOcreCircle.png" useMap={"#imgmapTop"} alt="Up White Arrow Ocre Circle" title="Go to the top" />

					<map name="imgmapTop">
						<area shape="circle" alt="Up White Arrow Ocre Circle" title="Go to the top" coords="25,25,25" href="#Home" />
					</map>
				</footer>
			</body>
		</html>
	);
}
